### PR TITLE
Test on Ruby 2.3.3 & 2.4.0

### PR DESCRIPTION
**Pull request by tricknotes**

### CODE REVIEW

**Comment by tricknotes** [comment]
@bolandrm How about this?

**Comment by bolandrm** [comment]
Hey, can you remove 2.0 and 2.1?

**Comment by tricknotes** [comment]
@bolandrm 
done https://github.com/sass/sassc-ruby/pull/52/commits/cf78ba3002f0375c91fcd88c4106ef502e4e39fd

**Comment by bolandrm** [comment]
Thanks

**Pull request merged**
