### PR TITLE
bump libsass to 3.4.0

### PR DESCRIPTION
**Pull request by sandlerr**

### CODE REVIEW

**Comment by sphinxc0re** [comment]
Bump! 😁 I really want this to be merged. Is there a problem with doing that?

**Comment by bolandrm** [comment]
Thanks!

**Comment by sphinxc0re** [comment]
@bolandrm shouldn't [this](https://rubygems.org/gems/sassc-rails) be updated as well?

**Comment by bolandrm** [comment]
We can update it eventually... until then you can just update the sassc-ruby version in your gemfile.

**Pull request merged**
