### PR TITLE
Update libsass to 3.4.5

### PR DESCRIPTION
**Pull request by fschwahn**

### CODE REVIEW

**Comment by fschwahn** [comment]
Tiny bump - 3.4.5 was released on the meantime, I could update the PR if you are interested in merging?

**Comment by bolandrm** [comment]
@fschwahn Can you update to 3.4.5?  I'll merge after that

**Comment by fschwahn** [comment]
Build failure is unrelated and addressed in #68 / #70 . On my development system, where I have an older version of sass in my lockfile, the tests passed.

**Comment by xzyfer** [comment]
I recommend against updating to 3.4.5. that release had some nasty
regressions.

On 11 Jul. 2017 2:29 am, "Fabian Schwahn" <notifications@github.com> wrote:

Build failure is unrelated and addressed in #68
<https://github.com/sass/sassc-ruby/pull/68> / #70
<https://github.com/sass/sassc-ruby/pull/70> . On my development system,
where I have an older version of sass in my lockfile, the tests passed.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/sass/sassc-ruby/pull/66#issuecomment-314160103>, or mute
the thread

**Comment by meowsus** [comment]
@xzyfer I'm curious if they would affect this library. @fschwahn did confirm the tests pass once #68/#70 are merged.

**Comment by xzyfer** [comment]
>I'm curious if they would affect this library
If this library expects Sass to compiled to CSS then it will :) This is probably the most significant issue https://github.com/sass/libsass/issues/2429

**Comment by xzyfer** [comment]
>did confirm the tests pass once

Are you testing against sass-spec? Because that should fail with 3.4.5.

**Comment by fschwahn** [comment]
I just ran the sassc-ruby tests (which you can find here: https://github.com/sass/sassc-ruby/tree/master/test), not sass-spec.

**Comment by meowsus** [comment]
@xzyfer I'm curious how one would run sass-spec against sassc-ruby. If you have the the time could you enlighten me?

**Comment by xzyfer** [comment]
I suggest running against sass-spec in CI to catch any known regressions that have been fixed on LibSass master. You can do that by cloning sass-spec, running bundle, then executing sass-spec.

```
ruby sass-spec.rb -V 3.4 --impl libsass -c /path/to/sassc-ruby spec/
```

Note: `-V 3.4` will vary depending on what version of LibSass you're binding too, either 3.4 or 3.5.

**Comment by meowsus** [comment]
@xzyfer thank you, I knew I was close yesterday when I was trying to test this locally. Very helpful!

**Comment by meowsus** [comment]
@bolandrm could we get sass-spec coverage added to the Travis build?

**Comment by bolandrm** [comment]
I don't think it's really necessary to have sass-spec for this repo.   The purpose of this repo is to integrate LibSass with ruby, not ensure that LibSass is outputting the correct CSS necessarily.

**Comment by bolandrm** [comment]
@xzyfer In the future, is there a good way for me to know when it's "safe" to update to a particular LibSass version?   I wonder if it would be valuable to somehow update the [release tag](https://github.com/sass/libsass/releases/tag/3.4.5) when significant regressions are discovered?

**Comment by xzyfer** [comment]
The safest way is to run sass spec in your CI. Many other integrationa to
just that including node-sass and perl-sass.

**Comment by bolandrm** [comment]
superseded by #78

**Pull request closed without merging**
