### PR TITLE
Show sass file on the top of backtrace

### PR DESCRIPTION
**Pull request by k0kubun**
When SyntaxError is raised, I want to see the broken sass file on error page. This is implemented in `Sass::SyntaxError` too.
Since we can know filename and lineno only from message, I implemented it by parsing it.

### CODE REVIEW

**Comment by k0kubun** [comment]
@bolandrm How do you think about this? Is there any blocker to merge? I want this patch to find what is wrong easily in development.

**Comment by bolandrm** [comment]
It looks good, no blockers.  I just need to get some time to review and test it and then I will merge.

**Comment by k0kubun** [comment]
Thank you for your comment! I'm looking forward to being reviewed.

**Comment by k0kubun** [comment]
@bolandrm ping? This prevents me from installing sassc-ruby from rubygems.org.

**Comment by k0kubun** [comment]
@bolandrm Could you have a try to merge this? We've tested this branch for a month and had no trouble.

**Comment by k0kubun** [comment]
@bolandrm ping? We want to stop using fork.

**Comment by k0kubun** [comment]
@bolandrm Hi. Any updates for this?

**Comment by k0kubun** [comment]
@bolandrm I've maintained this branch for a long time and had no trouble. Could you review and merge this?

**Comment by bolandrm** [comment]
Sorry for the delay, I'll merge this in when I do the next update for libsass 3.3.6.

**Comment by bolandrm** [comment]
Hey, I did merge this in, but I made some changes so that we're using the filename and line number information for libsass.  

https://github.com/sass/sassc-ruby/commit/73397b6217d0ef997535c4b44c3019bc8c08a2ac

it's working in my application, but let me know if you have any issues.  thanks for the contribution!

**Comment by k0kubun** [comment]
Hi. First of all, thank you for merging this PR! I confirmed your changes and changed my application to use sassc-ruby v1.10.0. I tried some invalid scss and it worked fine. I'll report an issue if I find!

**Pull request merged**
