### PR TITLE
Upgraded ffi gem from 1.9.6 to ">= 1.9"

### PR DESCRIPTION
**Pull request by jasnow**
Upgraded ffi gem from 1.9.6 to ">= 1.9" then ran "rake test --verbose" (all green).

### CODE REVIEW

**Comment by jasnow** [comment]
Checked Travis CI and they are all green.

**Comment by aried3r** [comment]
Hey @jasnow, I am also looking forward to this change, but I think we can relax the version constraint if it works with both 1.9 and 1.10 to just `~> 1.9`, what do you think?

It was added 4 years ago here: https://github.com/sass/sassc-ruby/commit/d2526f728586535a5681caee9d6d8a962b4c1e7d#diff-66b394e36e03994c8776467ce8f6ebb1R29 but I don't think it was completely on purpose to lock the version down like that, maybe @bolandrm knows more?

**Comment by jasnow** [comment]
@aried3r - then I would use ">= 1.9" because "~> 1.9" means 1.9.*.

**Comment by aried3r** [comment]
> then I would use ">= 1.9" because "~> 1.9" means 1.9.*.

I don't think so, `~> 1.9` means `['>=1.9', '<2']` AFAIK, while `>=1.9` would also allow 2, 3 etc. I'm fine with both options, though :)

https://robots.thoughtbot.com/rubys-pessimistic-operator
https://guides.rubygems.org/patterns/#pessimistic-version-constraint

**Comment by jasnow** [comment]
@aried3r, @bolandrm - I will be glad to change it to anything that includes the current release including removing the constraint.

**Comment by jasnow** [comment]
I will wait for official fix.

**Comment by aried3r** [comment]
This PR can be the official fix :)
Maybe leave the PR open so people can see it and maintainers can accept it?

**Pull request closed without merging**
