### PR TITLE
Add boolean script support

### PR DESCRIPTION
**Pull request by TeaSeaLancs**
This adds the missing ability to use booleans as arguments and returns from custom functions

### CODE REVIEW

**Comment by bolandrm** [comment]
Looks good, but i'm wondering why the CI did not check this...

**Comment by pedropereira** [comment]
Looking forward to having this one merged in as well :+1:

**Comment by TeaSeaLancs** [comment]
@bolandrm Is there anything I can do to address this, or to push the CI into action?

**Comment by bolandrm** [comment]
@TeaSeaLancs rebasing and pushing back up should probably trigger the CI

**Comment by TeaSeaLancs** [comment]
There we go :)

**Comment by bolandrm** [comment]
Thanks!

**Comment by TeaSeaLancs** [comment]
Hey Ryan,

Do you have any kind of ETA on when a version with this fix might be released? No pressure, we're just running into some trouble with our build processes using a forked version from github as opposed to the actual gem :)

Cheers,
Matt.

**Comment by bolandrm** [comment]
Matt - I just released 1.9.0.  Cheers.

**Comment by TeaSeaLancs** [comment]
You are a gentleman and a scholar, thanks so much :)

**Pull request merged**
